name: 'Check PR title(v2)'
on:
  pull_request:
    branches: ['master-v2', 'develop-v2']
    types: ['opened', 'reopened', 'edited', 'synchronize']

jobs:
  check_pr_title:
    name: Check PR title(v2)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4

      - name: Check PR title
        uses: rudderlabs/github-action-check-pr-title@v1.0.7
