name: 'Deploy to Cocoapods(v2)'

on:
  release:
    types: [created]

jobs:
  build:
    name: Deploy to Cocoapods
    runs-on: macos-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Publish to CocoaPod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push --allow-warnings
